name: PO1

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm install
        run: npm install

      -name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Docker MAKE IMAGE
        run: docker build -t alaldlftlr12/Po1:latest .

      - name: Docker PUSH
        run: docker push alaldlftlr12/Po1:latest